services:
  # app:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app

  banco:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: partners
    ports:
      - 3306:3306
    # volumes:
    #   - ./.docker/dbdata:/var/lib/mysql

networks:
  network1:
    name: luis_ubuntu
    external: true
